### ISSUE TITLE
Cannot reproduce the reported performance

### ISSUE THREAD

**Issue by sea2023time** [zaixizhang/DrugGPS_ICML23#2]
Hi Zaixi,

DrugGPS is a nice work. But the reported performance is not reproducible.   
Could you please provide a pretrained checkpoint?  

I think there may be something wrong about the logic of the codes.   
For example, https://github.com/zaixizhang/DrugGPS_ICML23/blob/main/utils/chemutils.py#L41.  (as mentioned in https://github.com/zaixizhang/FLAG/issues/9)   
So how is the reported performance achieved?   
Could you leave an explanation about this?   
Looking forward to your reply.

**Comment by zaixizhang** [comment]
Hi,

Thanks for your feedback! In our experiments, we observed that the normalization has little influence on the final generation quality. For the clarity of the code, I have uncommented the normalization. Thanks!

**Comment by sea2023time** [comment]
Hi,

Thanks for your reply.
We have different observations from yours and now we suspect the results reported in the paper.
Besides, with the normalization commented out or not, the performances are both far from the reported.
There are several logical mistakes in your codes, which I think you must be aware of, and we wonder how your work achieves the results reported in the paper.

Could you please provide convincing evidence for the results in the paper and your observation mentioned above?

**Comment by zaixizhang** [comment]
Hi,

Thanks for your response! Could you provide your results and observations? Since we are still working on this project, the GitHub repo contains the preliminary version of our work for reference.

**Comment by zaixizhang** [comment]
Hi,

I am interested in your results and could you provide more details so that I can help? We have done extensive experiment evaluations. But for the reasons of other projects and intellectual property, we can now provide the preliminary version. We will release the latest version soon.
