### ISSUE TITLE
Details About Pocket-based Clustered Split

### ISSUE THREAD

**Issue by qky18** [zaixizhang/DrugGPS_ICML23#3]
Hi Zaixi, thanks for pointing out the problem with sequence-based clustered split!
I'm really interested in different ways of dataset split, but after going through `PocketMatch` document, I can't find the exact definition of similarity score mentioned in your paper (perhaps it is `P-max_OP = C/B`?) and how the clustering is done.
Could you please share more details about the splitting or hopefully the data processing script? Thanks in advance!

**Comment by zaixizhang** [comment]
Hi Keyue, thanks for your question! Yes, the score P-max_OP is taken as the similarity score. In pocket-based clustered split, a set of initial centroids are sampled with pairwise similarity scores less than 0.75. The remaining pockets are compared with these centroids and assigned to the group with the highest similarity score (> 0.75). If there is no centroid that the pocket has an over 0.75 similarity score, the pocket is selected as a new centroid.

One example of pocket-based split is provided in [data/pocket_split.pt](https://github.com/zaixizhang/DrugGPS_ICML23/blob/b23e7863d4f4a3814f94441c48d50003142411af/data/pocket_split.pt)
