### ISSUE TITLE
FileNotFoundError:[Erron 2] No such file or directory:'. /data/crossdocked_pocket10_name2id.pt

### ISSUE THREAD

**Issue by YunyaJiang** [zaixizhang/DrugGPS_ICML23#4]
Hi, Zaixi，
Thanks for providing so great work!
Maybe I'm missing some information, I don't have a file：'crossdocked_pocket10_name2id.pt’
Cause error "FileNotFoundError:[Erron 2] No such file or directory:'. /data/crossdocked_pocket10_name2id.pt'. I checked the code and found no problem, could you please provide some help?
Thank you!

**Comment by FeilongWuHaa** [comment]
Delete the crossdocked_pocket10_processed.lmdb file in the ./data directory and run "python train.py" again. The data set will be re-preprocessed and the crossdocked_pocket10_name2id.pt and crossdocked_pocket10_processed.lmdb files will be generated.
